name: CI Pipeline

on:
  push:
    branches: [ staging, fix/** ]
  pull_request:
    branches: [ staging ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t https://hub.docker.com/repository/docker/ronfflex/projet-devops:${{ github.sha }} .

      - name: Run Tests
        run: docker run --rm https://hub.docker.com/repository/docker/ronfflex/projet-devops:${{ github.sha }} npm test

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Image to Docker Hub
        if: github.event_name != 'pull_request'
        run: docker push https://hub.docker.com/repository/docker/ronfflex/projet-devops:${{ github.sha }}
